name: pottullo
version: '${project.version}'
main: ua.mykolamurza.pottullo.Pottullo
api-version: 1.19
commands:
  accept:
    description: Accept your selected zone.
    usage: /accept
    aliases: acc
  info:
    description: Get information on the current privatized zone.
    usage: /info
  remove:
    description: Remove your privatization zone (doesn't destroy block).
    usage: /remove
